apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: diyaskart-app
  name: diyaskart-service
spec: 
  ports: 
    - 
      nodePort: 31100
      port: 8080
      targetPort: 8080
  selector: 
    app: diyaskart-app

